### ISSUE TITLE
After Initialization, is it possible to close the connection to the database?

### ISSUE THREAD

**Issue by erichowey** [wesen1/LuaORM#10]
My application threads which causes each instance to have its own unique connection to the database. After running `API.ORM:initialize()`, it it possible to close the connection to the database? Digging through the docs and source, it doesn't seem like this is possible.

**Comment by wesen1** [comment]
No, there is no way yet to close the database connection.
But it should be easy to add that functionality.

An empty `BaseDatabaseConnection:close()` method should be added, then the `LuaSQLConnection` could implement that method and call `self.connection:close()`.

**Comment by erichowey** [comment]
Thank you very much! PR #11 is open for your review :)

**Comment by erichowey** [comment]
Updated and tested PR #11 as requested.

**Comment by wesen1** [comment]
Closing this issue because https://github.com/wesen1/LuaORM/pull/11 was merged.
