### ISSUE TITLE
Non-Destructive Schema Settings

### ISSUE THREAD

**Issue by erichowey** [wesen1/LuaORM#5]
First and foremost, thank you for making this! I've been looking for a decent ORM for Lua and I finally found it!

One behavior I've been fighting with is that `CREATE TABLE IF NOT EXISTS` appears to be the default behavior every time a Model is instantiated and there appears to be no settings to disable this. I'm going to be running this ORM on a read only system and would prefer to keep the queries as light as possible. If 20+ tables are instantiated for single operation, this is going to add up quickly. I also don't want to risk any accidental schema changes if my user settings happen to be incorrect. 

I'm toying with a fork of this project. I'm happy to submit a PR if this is a change you're interested in bringing in.

**Comment by wesen1** [comment]
Sure, there should probably be a new constructor parameter for the `Model` class (maybe `_modelOptions`).

Then you could build a Model like this: `Model({ <table config> }, { createTable = true })`.
If the table should be created, then the old code should run, if the option is `false` then the table should only be validated.

**Comment by erichowey** [comment]
Thank you again! PR #12 has been created for your review.
